POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "pradeep", "password": "Pass1234!", "email": "pradeep@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "pradeep", "password": "Pass1234!" }

###

POST http://127.0.0.1:8000/logout 
Content-Type: application/json
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad

###

GET http://127.0.0.1:8000/validate_token 
Content-Type: application/json
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad

###

GET http://127.0.0.1:8000/items
Content-Type: application/json
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad

###

POST http://127.0.0.1:8000/item/
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad
Content-Type: application/json


{ "name": "Mango", "price": 23.98 }

###

PUT http://127.0.0.1:8000/item/4/
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad
Content-Type: application/json


{ "name": "Sweet Mango", "price": 44.98 }

###

DELETE http://127.0.0.1:8000/item/4/
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad
Content-Type: application/json


{ "name": "Sweet Mango", "price": 44.98 }
###

GET http://127.0.0.1:8000/summary/
Authorization: token 1d3483c76a1b5d7be0e134ebe94455d8add6fcad
Content-Type: application/json
